blank_issues_enabled: true
contact_links:
  - name: GitHub Community Support
    url: https://github.com/orgs/community/discussions
    about: Please ask and answer questions here.
  - name: GitHub Security Bug Bounty
    url: https://bounty.github.com/
    about: Please report security vulnerabilities here.
remote_theme: pages-themes/hacker@v0.2.0
plugins:
- jekyll-remote-theme
title: [First Person Shooter by Ibrahim Tariq]
